apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-school-deployment
  labels:
    app: easy-school
spec:
  replicas: 2  
  selector:
    matchLabels:
      app: easy-school
  template:
    metadata:
      labels:
        app: easy-school
    spec:
      containers:
      - name: easy-school
        image: peacerotimi6/easy-school:latest 
        ports:
        - containerPort: 80
        resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"