apiVersion: v1
kind: Service
metadata:
  name: easy-school-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 3000
  selector:
    app: easy-school
